### ISSUE TITLE
German translations

### ISSUE THREAD

**Issue by cedeber** [cedeber/mountain-bikers-club#40]
The German translation is not complete and need to be checked.

**Comment by freddiaN** [comment]
I'm on it

**Comment by freddiaN** [comment]
```
#: trail/templates/trail/main.html:115
msgid "Moving time"
```
What is meant by this? Because I don't think I can translate this literally.

**Comment by cedeber** [comment]
Hi, sorry I was off today. This is the time while you drive your bike, while you are moving. Technically this is how long you drive more than 1km/h. I think "Zeit in Bewegung" is a possible correct translation, isn't it?
