### ISSUE TITLE
Check for translations in templates

### ISSUE THREAD

**Issue by cedeber** [cedeber/mountain-bikers-club#45]
see #44

**Comment by Tititesouris** [comment]
Hello, I can see a few mistakes and missing translations in the French locale, should I edit the po file directly and propose a pull request?

**Comment by cedeber** [comment]
Hi. Yes, sure you can do it.

Just be avare that not all sentences in templates (HTML files) are currently well configured to appear in the po files (`{% trans 'a text' %}` => `python manage.py make messages`). This is what this issue is about.
